### ISSUE TITLE
Remote control

### ISSUE THREAD

**Issue by Joseph11024** [santacrab2/LGPETradeBot#2]
Hey just wondering if there are any plans to add remote control integration in the future?
The bot runs great but every once in a while it crashes or gets stuck and theres no way to fix it remotely.

**Comment by santacrab2** [comment]
I'm gonna guess you are referring to the "go for a stroll" error that's mentioned in the wiki. Remote control wouldn't fix it, when the game tries to find the pokeball controller it kills botbase so there is no connection to remote control. 

Also feel free to get to coding and do it yourself.
