### ISSUE TITLE
TradeModule.cs Line 22 Error

### ISSUE THREAD

**Issue by DarkKrimson** [santacrab2/LGPETradeBot#3]
The legality release fails to run and throws the error below. 

System.NullReferenceException: Object reference not set to an instance of an object.
   at SysBot.Pokemon.Discord.TradeModule..cctor() in C:\Users\j*****\source\repos\LGPETradeBot\SysBot.Pokemon.Discord\Commands\General\TradeModule.cs:line 22
   
Line 22:   
private static PokeTradeHub<PK8> hub = SysCordInstance.Self.Hub;"

**Comment by santacrab2** [comment]
Thanks for the heads up, i will investigate.

**Comment by santacrab2** [comment]
This has been resolved in the latest release.
